Repository googleinterns/SmallCity, pull requests merged in 2020-07, with the labels that each got.

#56 Change web.xml config for HTTPS redirect
  target/SmallCity-1/WEB-INF/web.xml
Labels: bug, small

#38 Interactive markers
  src/main/webapp/mapScript.js
  src/main/webapp/script.js
Labels: medium

#40 Refactor User logic to UserService and alter tests
  pom.xml
  src/main/java/com/google/sps/data/BusinessesService.java
  src/main/java/com/google/sps/data/SmallCityService.java
  src/main/java/com/google/sps/data/User.java
  src/main/java/com/google/sps/data/UserService.java
  src/main/java/com/google/sps/servlets/DataServlet.java
  src/test/java/com/google/sps/UserServiceTest.java
Labels: large

#37 Fix async by consolidation
  src/main/java/com/google/sps/data/SmallCityService.java
  src/main/java/com/google/sps/servlets/DataServlet.java
  src/main/webapp/script.js
Labels: large

#60 Move confidential https config
  src/main/webapp/WEB-INF/web.xml
Labels: bug, small

#59 Change Image Loading, Other Responsive Changes
  src/main/webapp/mapScript.js
  src/main/webapp/paginationScript.js
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: enhancement, medium

#63 Loader implementation
  src/main/webapp/index.html
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: enhancement, medium

#66 Made the algorithm to delete big businesses from results less complex
  src/main/java/com/google/sps/data/BusinessesService.java
  src/main/java/com/google/sps/data/SmallCityService.java
  src/test/java/com/google/sps/BigBusinessesTest.java
Labels: enhancement, medium

#71 Set up API keys in an env file
  .gcloudignore
  .gitignore
  pom.xml
  src/main/java/com/google/sps/data/BusinessesService.java
  src/main/java/com/google/sps/data/UserService.java
  src/test/java/com/google/sps/UserServiceTest.java
Labels: bug, enhancement, small

#39 Add big businesses to database
  pom.xml
  src/main/java/com/google/sps/data/BusinessesService.java
  src/main/java/com/google/sps/data/SmallCityService.java
Labels: enhancement, xl

#64 Add links to website buttons
  src/main/java/com/google/sps/data/BusinessesService.java
  src/main/java/com/google/sps/data/Listing.java
  src/main/webapp/script.js
  src/main/webapp/style.css
  src/test/java/com/google/sps/BigBusinessesTest.java
Labels: enhancement, medium

#67 Implement isValidInput() function
  src/main/java/com/google/sps/data/UserService.java
  src/main/webapp/index.html
  src/main/webapp/script.js
Labels: enhancement, small

#77 Cache small businesses using Google's datastore API
  src/main/java/com/google/sps/data/BusinessesService.java
  src/main/java/com/google/sps/data/SmallCityService.java
  src/main/java/com/google/sps/data/User.java
  src/main/java/com/google/sps/data/UserService.java
  src/main/java/com/google/sps/servlets/DataServlet.java
Labels: enhancement, large

#70 Add "Image Not Found" Images
  src/main/webapp/images/image_not_found_one.png
  src/main/webapp/images/image_not_found_two.png
  src/main/webapp/paginationScript.js
  src/main/webapp/script.js
Labels: enhancement

#76 Product search implementation
  src/main/java/com/google/sps/data/BusinessesService.java
  src/main/java/com/google/sps/data/SearchObject.java
  src/main/java/com/google/sps/data/SmallCityService.java
  src/main/java/com/google/sps/servlets/DataServlet.java
  src/main/webapp/index.html
  src/main/webapp/script.js
  src/main/webapp/style.css
  src/test/java/com/google/sps/UserServiceTest.java
Labels: enhancement, xl

#80 Implement reverseGeocodeGeolocation() function
  src/main/webapp/mapScript.js
  src/main/webapp/script.js
Labels: enhancement, small

#81 Storing listings and location of the user for their local search
  src/main/webapp/mapScript.js
  src/main/webapp/script.js
Labels: enhancement, medium
