Repository googleinterns/SmallCity, pull requests merged in 2020-08, with the labels that each got.

#85 Move website logic to pagination script
  src/main/java/com/google/sps/data/BusinessesService.java
  src/main/java/com/google/sps/data/Listing.java
  src/main/webapp/index.html
  src/main/webapp/paginationScript.js
  src/main/webapp/script.js
  src/test/java/com/google/sps/BigBusinessesTest.java
Labels: enhancement, medium

#88 Final Frontend Changes
  src/main/webapp/index.html
  src/main/webapp/mapScript.js
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: enhancement, xl

#89 changed localStorage to sessionStorage
  src/main/webapp/script.js
Labels: enhancement, small

#90 Misc. Final Bug Fixes
  src/main/webapp/index.html
  src/main/webapp/mapScript.js
  src/main/webapp/script.js
Labels: small

#87 Updated README file
  README.md
  envSample
Labels: enhancement

#97 Update README.md
  README.md
Labels: enhancement
